# -*- coding: utf-8 -*-
{
    'name': 'MECIS',
    'version': '15.0.1.0',
    'category': 'Studio',
    'description': u"""
MECIS - A comprehensive platform to manage medical equipment in hospitals.
Includes maintenance, calibration, loan tracking, and document management.
""",
    'author': 'Thangnh',
    'price': '399.0',
    'currency': 'USD',
    'depends': [
        'base',
        'documents',
        'hr',
        'hr_maintenance',
        'mail',
        'maintenance',
        'mrp_maintenance',
        'quality',
        'quality_control',
        'sign',
        'stock',
        'web',
        'web_studio',
    ],
    'data': [
        'data/report_paperformat.xml',
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_act_window_view.xml',
        'data/ir_actions_report.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_rule.xml',
        'data/ir_default.xml',
    ],
    'images': ['static/description/cover.jpg'],
    'installable': True,
    'application': False,
    'license': 'OPL-1',
}
